import type { Profile } from "@prisma/client";

export const profiles: {
  id: Profile["id"];
  userId: Profile["user_id"];
  fullname: Profile["fullname"];
  email: Profile["email"];
  gender?: Profile["gender"];
  phone?: Profile["phone"];
  isPublic: Profile["is_public"];
}[] = [
  {
    id: 1,
    fullname: "Jason Talley",
    email: "jason.talley@email.com",
    userId: 1,
    gender: "M",
    isPublic: false,
  },
  {
    id: 2,
    fullname: "Celine Preston",
    email: "celine.preston@email.com",
    userId: 2,
    phone: "6900000002",
    isPublic: true,
  },
  {
    id: 3,
    fullname: "Natalie Coleman",
    email: "natalie.coleman@email.com",
    userId: 3,
    gender: "F",
    phone: "6900000003",
    isPublic: true,
  },
  {
    id: 4,
    fullname: "Melvin Reese",
    email: "melvin.reese@email.com",
    userId: 10,
    isPublic: true,
  },
  {
    id: 5,
    fullname: "Gregory Tanner",
    email: "gregory.tanner@email.com",
    userId: 11,
    gender: "M",
    phone: "6900000005",
    isPublic: true,
  },
  {
    id: 6,
    fullname: "Wendy Flower",
    email: "wendy.flower@email.com",
    userId: 12,
    gender: "F",
    phone: "6900000006",
    isPublic: true,
  },
  {
    id: 7,
    fullname: "Thomas Buckley",
    email: "thomas.buckley@email.com",
    userId: 13,
    isPublic: true,
  },
  {
    id: 8,
    fullname: "John Ellwood",
    email: "john.ellwood@email.com",
    userId: 14,
    gender: "M",
    phone: "6900000008",
    isPublic: false,
  },
  {
    id: 9,
    fullname: "Mark Bowman",
    email: "mark.bowman@email.com",
    userId: 15,
    gender: "M",
    isPublic: true,
  },
  {
    id: 10,
    fullname: "Helen Byrne",
    email: "helen.byrne@email.com",
    userId: 16,
    phone: "6900000010",
    isPublic: true,
  },
  {
    id: 11,
    fullname: "Steve Wickens",
    email: "steve.wickens@email.com",
    userId: 17,
    isPublic: false,
  },
  {
    id: 12,
    fullname: "Anna Huffman",
    email: "anna.huffman@email.com",
    userId: 18,
    isPublic: false,
  },
  {
    id: 13,
    fullname: "Denice Hatfield",
    email: "denice.hatfield@email.com",
    userId: 19,
    gender: "F",
    isPublic: true,
  },
  {
    id: 14,
    fullname: "Clyde Robinson",
    email: "clyde.robinson@email.com",
    userId: 20,
    gender: "M",
    phone: "6900000014",
    isPublic: false,
  },
  {
    id: 15,
    fullname: "Emily Smith",
    email: "emily.smith@email.com",
    userId: 21,
    gender: "F",
    phone: "6900000015",
    isPublic: true,
  },
  {
    id: 16,
    fullname: "Michael Brown",
    email: "michael.brown@email.com",
    userId: 100,
    gender: "M",
    isPublic: true,
  },
  {
    id: 17,
    fullname: "Jessica Johnson",
    email: "jessica.johnson@email.com",
    userId: 101,
    gender: "F",
    isPublic: true,
  },
  {
    id: 18,
    fullname: "Matthew Davis",
    email: "matthew.davis@email.com",
    userId: 102,
    gender: "M",
    phone: "6900000018",
    isPublic: true,
  },
  {
    id: 19,
    fullname: "Sarah Taylor",
    email: "sarah.taylor@email.com",
    userId: 103,
    isPublic: false,
  },
  {
    id: 20,
    fullname: "Christopher Anderson",
    email: "christopher.anderson@email.com",
    userId: 104,
    gender: "M",
    isPublic: false,
  },
  {
    id: 21,
    fullname: "Olivia Williams",
    email: "olivia.williams@email.com",
    userId: 105,
    gender: "F",
    isPublic: true,
  },
  {
    id: 22,
    fullname: "David Rodriguez",
    email: "david.rodriguez@email.com",
    userId: 106,
    gender: "M",
    isPublic: true,
  },
  {
    id: 23,
    fullname: "Elizabeth Thompson",
    email: "elizabeth.thompson@email.com",
    userId: 107,
    isPublic: true,
  },
  {
    id: 24,
    fullname: "James Martin",
    email: "james.martin@email.com",
    userId: 108,
    gender: "M",
    phone: "6900000024",
    isPublic: true,
  },
  {
    id: 25,
    fullname: "Benjamin Franklin",
    email: "benjamin.franklin@email.com",
    userId: 109,
    gender: "M",
    phone: "6900000025",
    isPublic: true,
  },
  {
    id: 26,
    fullname: "Rachel Green",
    email: "rachel.green@email.com",
    userId: 110,
    gender: "F",
    isPublic: true,
  },
  {
    id: 27,
    fullname: "William Thompson",
    email: "william.thompson@email.com",
    userId: 111,
    isPublic: true,
  },
  {
    id: 28,
    fullname: "Ashley Roberts",
    email: "ashley.roberts@email.com",
    userId: 112,
    gender: "F",
    isPublic: false,
  },
  {
    id: 29,
    fullname: "John Doe",
    email: "john.doe@email.com",
    userId: 113,
    isPublic: true,
  },
  {
    id: 30,
    fullname: "Maria Green",
    email: "maria.green@email.com",
    userId: 114,
    gender: "F",
    isPublic: true,
  },
  {
    id: 31,
    fullname: "Sophia Jones",
    email: "sophia.jones@email.com",
    userId: 115,
    isPublic: true,
  },
  {
    id: 32,
    fullname: "Ethan Parker",
    email: "ethan.parker@email.com",
    userId: 116,
    gender: "M",
    phone: "6900000030",
    isPublic: true,
  },
  {
    id: 33,
    fullname: "Richard Wright",
    email: "richard.wright@email.com",
    userId: 117,
    gender: "M",
    isPublic: false,
  },
  {
    id: 34,
    fullname: "Charles Miller",
    email: "charles.miller@email.com",
    userId: 118,
    isPublic: true,
  },
  {
    id: 35,
    fullname: "Joseph Wilson",
    email: "joseph.wilson@email.com",
    userId: 119,
    gender: "M",
    isPublic: true,
  },
  {
    id: 36,
    fullname: "Thomas Moore",
    email: "thomas.moore@email.com",
    userId: 120,
    gender: "M",
    isPublic: true,
  },
  {
    id: 37,
    fullname: "Paul Harris",
    email: "paul.harris@email.com",
    userId: 121,
    isPublic: true,
  },
  {
    id: 38,
    fullname: "Donald Clark",
    email: "donald.clark@email.com",
    userId: 122,
    gender: "M",
    phone: "6900000036",
    isPublic: true,
  },
  {
    id: 39,
    fullname: "Steven Lewis",
    email: "steven.lewis@email.com",
    userId: 123,
    gender: "M",
    isPublic: true,
  },
  {
    id: 40,
    fullname: "Kenneth Allen",
    email: "kenneth.allen@email.com",
    userId: 124,
    gender: "M",
    isPublic: true,
  },
  {
    id: 41,
    fullname: "Gary Hall",
    email: "gary.hall@email.com",
    userId: 125,
    isPublic: true,
  },
  {
    id: 42,
    fullname: "Larry Walker",
    email: "larry.walker@email.com",
    userId: 126,
    isPublic: false,
  },
  {
    id: 43,
    fullname: "Jeffrey King",
    email: "jeffrey.king@email.com",
    userId: 127,
    gender: "M",
    isPublic: true,
  },
];
