import type { StudentCourse } from "@prisma/client";

const randomPassingGrade = () => {
  const n = Math.random() * 14;
  if (n < 2) return 5;
  if (n < 5) return 6;
  if (n < 8) return 7;
  if (n < 11) return 8;
  if (n < 13) return 9;
  return 10;
};
const randomFailingGrade = () => {
  const n = Math.random() * 14;
  if (n < 1) return 1;
  if (n < 2) return 2;
  if (n < 5) return 3;
  if (n < 9) return 4;
  return null;
};

const generateRelations = (
  studentId: number,
  semester: number,
  electives: number[],
  threshhold: number,
) => {
  const pass = Math.random() < threshhold;
  const compulsories = [
    [1, 15, 21],
    [2, 12, 8],
    [4, 3, 14, 26],
    [9, 11, 28],
    [30, 33, 29],
    [16, 6, 7],
    [34, 17],
    [24, 25, 22],
  ];

  const comps = compulsories
    .flatMap((semComp, i) =>
      i + 1 > semester
        ? undefined
        : semComp.map((comp) => {
            return {
              studentId: studentId,
              courseId: comp,
              grade: pass ? randomPassingGrade() : randomFailingGrade(),
              isEnrolled: true,
              isFollowing: true,
              isDrafted: false,
            };
          }),
    )
    .filter(Boolean) as StudentCoursesT;

  const elecs = electives.map((elec) => ({
    studentId: studentId,
    courseId: elec,
    grade: pass ? randomPassingGrade() : randomFailingGrade(),
    isEnrolled: true,
    isFollowing: true,
    isDrafted: false,
  }));

  return [...comps, ...elecs];
};

type StudentCoursesT = {
  studentId: StudentCourse["student_id"];
  courseId: StudentCourse["course_id"];
  grade: StudentCourse["grade"];
  isEnrolled: StudentCourse["is_enrolled"];
  isFollowing: StudentCourse["is_following"];
  isDrafted: StudentCourse["is_drafted"];
}[];

export const studentCourses: StudentCoursesT = [
  // {
  //   studentId: 1,
  //   courseId: 1,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 15,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 21,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 2,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 12,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 8,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 4,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 3,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 14,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 26,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 9,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 11,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 28,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 30,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 33,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 29,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 16,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 6,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 7,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 34,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 17,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 24,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 25,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 22,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 32,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 31,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 5,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 1,
  //   courseId: 27,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // //
  // {
  //   studentId: 2,
  //   courseId: 1,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 15,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 21,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 2,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 12,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 8,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 4,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 3,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 14,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 26,
  //   grade: randomFailingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 9,
  //   grade: randomFailingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 11,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 28,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 30,
  //   grade: randomFailingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 33,
  //   grade: randomFailingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 29,
  //   grade: randomFailingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 16,
  //   grade: randomFailingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 6,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 7,
  //   grade: randomFailingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 34,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 17,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 24,
  //   grade: randomFailingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 25,
  //   grade: randomFailingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 22,
  //   grade: randomFailingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 13,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 23,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 20,
  //   grade: randomFailingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 2,
  //   courseId: 18,
  //   grade: randomFailingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // //
  // {
  //   studentId: 3,
  //   courseId: 1,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 15,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 21,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 2,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 12,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 8,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 4,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 3,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 14,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 26,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 9,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 11,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 28,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 30,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 33,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 29,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 16,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 6,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 7,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 34,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 17,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 24,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 25,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 22,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 10,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 19,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 20,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  // {
  //   studentId: 3,
  //   courseId: 27,
  //   grade: randomPassingGrade(),
  //   isEnrolled: true,
  //   isFollowing: true,
  //   isDrafted: false,
  // },
  //
  ...generateRelations(1, 8, [32, 31, 5, 27], 1),
  ...generateRelations(2, 8, [13, 23, 20, 18], 0.8),
  ...generateRelations(3, 8, [10, 19, 20, 27], 1),
  ...generateRelations(4, 8, [32, 19, 20, 18], 0.8),
  ...generateRelations(5, 8, [32, 23, 5, 27], 0.8),
  ...generateRelations(6, 8, [13, 19, 5, 18], 0.8),
  ...generateRelations(7, 8, [10, 31, 5, 18], 0.8),
  ...generateRelations(8, 8, [10, 23, 20, 27], 0.8),
  ...generateRelations(9, 8, [10, 31, 5, 27], 0.8),
  ...generateRelations(10, 8, [13, 31, 20, 27], 1),
  ...generateRelations(11, 8, [32, 23, 5, 18], 0.8),
  {
    studentId: 12,
    courseId: 35,
    grade: null,
    isEnrolled: true,
    isFollowing: true,
    isDrafted: false,
  },
  ...generateRelations(13, 8, [32, 19, 5, 18], 1),
  {
    studentId: 13,
    courseId: 35,
    grade: 9,
    isEnrolled: true,
    isFollowing: true,
    isDrafted: false,
  },
  ...generateRelations(14, 8, [10, 23, 5, 27], 0.8),
  ...generateRelations(15, 8, [13, 23, 5, 27], 0.8),
  ...generateRelations(16, 8, [13, 19, 20, 18], 0.8),
  ...generateRelations(17, 8, [32, 19, 5, 27], 1),
  {
    studentId: 17,
    courseId: 35,
    grade: null,
    isEnrolled: true,
    isFollowing: true,
    isDrafted: false,
  },
  ...generateRelations(18, 6, [32, 31, 20], 0.8),
  ...generateRelations(19, 6, [32, 31, 5], 0.8),
  ...generateRelations(20, 6, [13, 23, 20], 0.8),
  ...generateRelations(21, 4, [10], 0.8),
  ...generateRelations(22, 4, [13], 0.8),
  ...generateRelations(23, 4, [10], 0.8),
  ...generateRelations(24, 4, [], 0.8),
  ...generateRelations(25, 2, [], 0.8),
  ...generateRelations(26, 2, [], 0.8),
  ...generateRelations(27, 2, [], 0.8),
  {
    studentId: 28,
    courseId: 35,
    grade: null,
    isEnrolled: true,
    isFollowing: true,
    isDrafted: false,
  },
];
